dist: xenial
language: python
python:
  - '3.6'
services:
  - docker
git:
  submodules: false
stages:
  - test
  - build
  - run
jobs:
  include:
    - stage: test
      name: "test file"
      script: python core.py
    - stage: build
      name: "build image"
      script: 
        - docker build -t noder/core:build-${TRAVIS_JOB_ID} . 
    - stage: run
      name: "run image"
      script: 
        - docker build -t noder/core:build-${TRAVIS_JOB_ID} . 
        - docker run -i -t noder/core:build-${TRAVIS_JOB_ID} echo hello linux
        - docker login -u ${docker_username} -p ${docker_password}
        - docker tag noderrobot/core:build-${TRAVIS_JOB_ID} noderrobot/core:build-${TRAVIS_JOB_ID}
        - docker push noderrobot/core:build-${TRAVIS_JOB_ID}
        - docker logout
        - docker ps -a
    - stage: Deploy on branches
      name: "Deploy on branches"
      deploy:
        - provider: script
          script: bash scripts/deploy.sh
          skip_cleanup: true
script: true