dist: xenial
language: python
sudo: true
python:
  - '3.6'
services:
  - docker
git:
  submodules: false
stages:
  - test
  - build
  - run
jobs:
  include:
    - stage: test
      name: "test file"
      script: python core.py
    - stage: build
      name: "build image"
      script: 
        - docker build -t noder/core:build-${TRAVIS_JOB_ID} . 
    - stage: run
      name: "run image"
      script: 
        - docker build -t noder/core:build-${TRAVIS_JOB_ID} . 
        - docker run -i -t noder/core:build-${TRAVIS_JOB_ID} echo hello linux
        - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
        - docker tag noderrobot/core:build-${TRAVIS_JOB_ID} noderrobot/core:build-${TRAVIS_JOB_ID}
        - docker push noderrobot/core:build-${TRAVIS_JOB_ID}
        - docker logout
        - docker ps -a
script: 
- echo "52.5.185.86 registry-1.docker.io" > /etc/hosts
